### ISSUE TITLE
Suggestions for duplication testing

### ISSUE THREAD

**Issue by akochari** [pekrau/Publications#313]
When going through many-many entries we added, I noticed that we managed to add some duplicates. I investigated this a bit further. Some thoughts on duplicates:

**When fetching data automatically:**
Currently, when I try to add a duplicate entry with PMID (have not tried DOI), it simply updates the existing entry without any warning. This way, a user may think that they are adding a new entry, but in fact they are modifying an existing (possibly better annotated) entry.
I think if an entry with an existing PMID/DOI is added, a more expected behavior would be either 1. it is not possible to add an entry, the user is given a warning that such entry already exists and is directed to go and edit the existing entry; or 2. the user is warned that such entry already exists and then is given a choice of either agreed to update the existing entry with new info or not adding this new entry now.

**Adding an entry manually:**
Currently, when an entry is added manually, DOI can be provided. We try to always provide a DOI. If an entry with such a DOI already exists in the database, currently a new entry is created (NB: not updated like I described in case of automatic entry above). It would be good if the user is warned. And again either the system would refuse to add a new entry (and ask to edit the existing one instead) or at least warn and ask if the existing one should be updated.

**Comment by pekrau** [comment]
Updating an existing entry is done non-destructively, or that is at least the intention. That is, adds bibliographic data that wasn't there.

About duplications: there is already a procedure for identifying potential duplicates. Look in the pull-down menu "Publications", item "Duplicates". This runs a procedure which tries to find duplicates based on similarity of titles. It's a fuzzy test, so false positives do occur. Once you have the list, one can go through it manually.

I think this is sufficient. Having extra logic to test DOI when adding manually is overdoing it. Better to use Fetch. Or do the Duplication check with some regularity. Also, DOI test does not catch a frequent cause of duplicates, namely BioArxiv and "real" publication.

I do notice that there seem to be some duplicates in the Covid-19 database.

**Comment by pekrau** [comment]
I have decided to keep the current logic of `fetch`, namely that pre-existing publications will be automatically updated. The reason is that when the facilities add their publications, they use `fetch` and their relevant labels are pre-set for the operation. The expected behavior is that these labels will then be added, thereby modifying the entry. Previous annotation is kept, so updating should not remove anything.

Also, with the introduction of the Researcher entity (not yet deployed), the update will associate an existing publication with researchers, if ORCID is given in the PubMed entry. This is good.
